version: "3.1"
services:
  task:
    build:
      context: .
      dockerfile: Dockerfile
    image: backaged/go-hexagonal-architecture:v1
    command: serve-rest -c "/etc/config.yaml"
    ports:
      - 8000:8000
    depends_on:
      - mongo
      - redis
    volumes:
      - ./config.yaml:/etc/config.yaml
    
  redis:
    image: "redis:alpine"
    restart: always
    ports: 
      - "6379:6379"

  mongo:
    image: mongo:4
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./storage/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    