version: "3.1"
services:
  mongo:
    image: mongo:4
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./storage/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  task:
    build:
      context: .
      dockerfile: Dockerfile
    image: BackAged/go-hexagonal-architecture:v1
    command: serve -c "/etc/config.yaml"
    ports:
      - 8000:8000
    depends_on:
      - mongo
    volumes:
      - ./config.yaml:/etc/config.yaml